name: "Provisionamento em Dev"

on:
  push:
    branches:
      - desenvolvimento

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: "dev"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "bucket-armazenamento-terraform"
      aws-lock-dynamodb-table: "tabela_bloqueio_execucao"
