name: "PIPELINE: Terraform"

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      aws-assume-role-arn:
        type: string
        required: true
      aws-statefile-s3-bucket:
        type: string
        required: true
      aws-lock-dynamodb-table:
        type: string
        required: true
      aws-region:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      clean_statefile_bucket:
        description: "Limpar bucket de statefile do Terraform?"
        required: false
        default: "false"

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: CHECKOUT DO REPOSITÓRIO
        uses: actions/checkout@v4

      - name: CONFIGURANDO TERRAFORM
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1

      - name: CONFIGURAÇÃO DO AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-assume-role-arn }}
          role-session-name: GiiHubv_to_AWS_via_FederatedOIDC
          aws-region: ${{ inputs.aws-region }}

      - name: INICIALIZANDO TERRAFORM
        run: |
          cd terraform  
          terraform init \
            -backend-config="bucket=${{ inputs.aws-statefile-s3-bucket }}" \
            -backend-config="key=${{ inputs.environment }}/terraform.tfstate" \
            -backend-config="dynamodb_table=${{ inputs.aws-lock-dynamodb-table }}" \
            -backend-config="region=${{ inputs.aws-region }}"

      - name: LIMPAR BUCKET DE STATEFILE (opcional)
        if: ${{ github.event.inputs.clean_statefile_bucket == 'true' }}
        run: |
          aws s3 rm s3://${{ inputs.aws-statefile-s3-bucket }} --recursive

      - name: VALIDAÇÃO DO TERRAFORM
        run: |
          cd terraform
          terraform validate

      - name: PLANJAMENTO DO TERRAFORM
        id: terraform_plan
        run: |
          cd terraform
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
            terraform plan -var-file="./ambientes/${{ inputs.environment }}/terraform.tfvars" -out=${{ inputs.environment }}.plan

      - name: EXECUTANDO O TERRAFORM
        id: terraform_apply
        run: |
          cd terraform
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}
          terraform apply -auto-approve "${{ inputs.environment }}.plan"
      - name: CONFIGURAÇÃO DO AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-assume-role-arn }}
          role-session-name: Github_Clean_Statefile
          aws-region: ${{ inputs.aws-region }}

      - name: LIMPAR BUCKET DE STATEFILE
        run: |
          aws s3 rm s3://${{ inputs.aws-statefile-s3-bucket }} --recursive
